In [16]:
import numpy as np

In [22]:
A = np.array([[0,1],[2,3],[4,5]])
B = np.array([[0,1,2,3,],[4,5,6,7]])
print(f"A=\n {A}")
print(f"B=\n {B}")

A=
 [[0 1]
 [2 3]
 [4 5]]
B=
 [[0 1 2 3]
 [4 5 6 7]]


In [24]:
C = A@B
C

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [29]:
C.max()

np.int64(47)